[webservers]
web01 ansible_host=10.0.1.10
web02 ansible_host=10.0.1.11

[databases]
db01 ansible_host=10.0.2.10

[monitoring]
monitor01 ansible_host=10.0.3.10

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
